apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description | default("A Quarkus gRPC microservice", true) }}
  annotations:
    backstage.io/source-location: url:https://${{ values.ghHost }}/${{ values.ghOwner }}/${{ values.repoName }}
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    backstage.io/techdocs-ref: dir:.
    janus-idp.io/tekton: ${{ values.name }}
    github.com/project-slug: ${{ values.ghOwner }}/${{ values.repoName }}
    argocd/app-selector: app.kubernetes.io/instance=${{ values.name }}
    nexus-repository-manager/docker.image-name: ${{ values.imageOrg }}/${{ values.imageName if values.imageName else values.name }}
  links:
    - url: https://devspaces.apps.tallgeese.ultra.lab/#https://${{ values.ghHost }}/${{ values.ghOwner }}/${{ values.repoName }}
      title: Open in Dev Spaces
      icon: catalog
      type: ide
  tags:
    - quarkus
    - grpc
    - java
    - openshift
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: experimental
