apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quay-push-credentials
  namespace: ${{ values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: quay-push-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"{{ .registry }}":{"username":"{{ .username }}","password":"{{ .token }}","auth":"{{ printf "%s:%s" .username .token | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: platform/quay-push-credentials
        property: username
    - secretKey: token
      remoteRef:
        key: platform/quay-push-credentials
        property: token
    - secretKey: registry
      remoteRef:
        key: platform/quay-push-credentials
        property: registry
