# gRPC server configuration
quarkus.grpc.server.port=9000
quarkus.grpc.server.use-separate-server=true

# HTTP server configuration
quarkus.http.port=8080

# Container image configuration
quarkus.container-image.registry=${{ values.imageRegistry }}
quarkus.container-image.group=${{ values.imageOrg }}
quarkus.container-image.name=${{ values.imageName }}
quarkus.container-image.tag=latest
quarkus.container-image.builder=jib

# Application name
quarkus.application.name=${{ values.name }}
