apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
    app.kubernetes.io/name: ${{ values.name }}
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/part-of: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
        app.kubernetes.io/name: ${{ values.name }}
        app.kubernetes.io/instance: ${{ values.name }}
        backstage.io/kubernetes-id: ${{ values.name }}
    spec:
      containers:
        - name: ${{ values.name }}
          image: ${{ values.image }}:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
