apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
    app.kubernetes.io/name: ${{ values.name }}
    app.kubernetes.io/instance: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  selector:
    app: ${{ values.name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 9000
      targetPort: 9000
      protocol: TCP
